using Microsoft.CodeAnalysis;

using static Macaron.PropertyAccessor.Tests.Helper;

namespace Macaron.PropertyAccessor.Tests;

[TestFixture]
public class PropertyAccessorGeneratorDiagnosticTests
{
    [Test]
    public void Should_ReportDiagnostic_When_FieldTypeCannotConvertToSpecifiedPropertyType()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            public partial class Foo
            {
                [Get(Type = typeof(int))]
                private string _answer = "";
            }
            """,
            expected: "",
            out var diagnostics
        );

        Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic =>
            diagnostic.Id == "MPROP0005" &&
            diagnostic.GetMessage().Contains("string") &&
            diagnostic.GetMessage().Contains("int")
        ));
    }

    [Test]
    public void Should_ReportDiagnosticAndNotGenerateProperty_When_GetAndGetSetAreUsedTogether()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            public partial class Foo
            {
                [Get, GetSet]
                private int _invalid = 42;

                [Get]
                private int _valid = 42;
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.PropertyAccessor.Tests
            {
                partial class Foo
                {
                    public int Valid
                    {
                        get => _valid;
                    }
                }
            }

            """,
            out var diagnostics
        );

        Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic =>
            diagnostic.Id == "MPROP0006"
            && diagnostic.Severity == DiagnosticSeverity.Error
            && diagnostic.GetMessage().Contains("_invalid")
        ));
    }

    [Test]
    public void Should_ReportDiagnostic_When_GeneratedPropertyNameIsEmpty()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            public partial class Foo
            {
                [Get] private readonly int _ = null!;
            }
            """,
            expected: "",
            out var diagnostics
        );

        Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.Id == "MPROP0001"));
    }

    [Test]
    public void Should_ReportDiagnostic_When_GeneratedPropertyNameConflictsWithFieldName()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            public partial class Foo
            {
                [Get] private readonly int Answer = null!;
            }
            """,
            expected: "",
            out var diagnostics
        );

        Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.Id == "MPROP0002"));
    }

    [Test]
    public void Should_ReportError_When_ClassLevelPrefixRegexIsInvalid()
    {
         AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            [PropertyGenerationDefaults(PrefixPattern = "[invalid")]
            public partial class Foo
            {
                [Get]
                private int _answer = 42;
            }
            """,
            expected: "",
            out var diagnostics
        );

        Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic =>
            diagnostic.Id == "MPROP0003" &&
            diagnostic.GetMessage().Contains("[invalid")
        ));
    }

    [Test]
    public void Should_ReportDiagnostic_When_FieldLevelPropertyGenerationDefaultsIsUsed()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            public partial class Foo
            {
                [PropertyGenerationDefaults(PrefixPattern = "_"), Get]
                private int _answer = 42;
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.PropertyAccessor.Tests
            {
                partial class Foo
                {
                    public int Answer
                    {
                        get => _answer;
                    }
                }
            }

            """,
            out var diagnostics
        );

        Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.Id == "CS0592"));
    }

    [Test]
    public void Should_ReportDiagnostic_When_StaticFieldUsesComplexPrefixPattern()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            [PropertyGenerationDefaults(PrefixPattern = @"^(m_|_|s_)")]
            public partial class Foo
            {
                [Get]
                private int m_answer1 = 42;

                [Get]
                private int _answer2 = 42;

                [Get]
                private static int s_answer3 = 42;

                [Get]
                private int normalField = 42;
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.PropertyAccessor.Tests
            {
                partial class Foo
                {
                    public int Answer1
                    {
                        get => m_answer1;
                    }

                    public int Answer2
                    {
                        get => _answer2;
                    }

                    public int NormalField
                    {
                        get => normalField;
                    }
                }
            }

            """,
            out var diagnostics
        );

        Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.Id == "MPROP0004"));
    }

    [Test]
    public void Should_ReportDiagnosticAndNotGenerateProperty_When_StaticFieldWouldGenerateProperty()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            public partial class Foo
            {
                [Get]
                private static int s_getter = 1;

                [GetSet]
                private static int s_setter = 2;

                [Get]
                private int _answer = 42;
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.PropertyAccessor.Tests
            {
                partial class Foo
                {
                    public int Answer
                    {
                        get => _answer;
                    }
                }
            }

            """,
            out var diagnostics
        );

        Assert.That(diagnostics.Count(diagnostic => diagnostic.Id == "MPROP0004"), Is.EqualTo(2));
    }
}
