using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Macaron.PropertyAccessor.Tests;

[TestFixture]
public class PropertyAccessorGeneratorTests
{
    private static void AssertGeneratedCode(
        string sourceCode,
        string expected,
        out ImmutableArray<Diagnostic> diagnostics
    )
    {
        (diagnostics, var generatedCode) = CompileAndGetResults(sourceCode);

        Assert.That(generatedCode.ReplaceLineEndings(), Is.EqualTo(expected.ReplaceLineEndings()));
    }

    private static void AssertGeneratedCode(
        string sourceCode,
        string expected
    )
    {
        var (_, generatedCode) = CompileAndGetResults(sourceCode);

        Assert.That(generatedCode.ReplaceLineEndings(), Is.EqualTo(expected.ReplaceLineEndings()));
    }

    private static (ImmutableArray<Diagnostic> diagnostics, string generatedCode) CompileAndGetResults(string sourceCode)
    {
        var attributeAssembly = typeof(GetSetAttribute).Assembly;
        var references = AppDomain
            .CurrentDomain
            .GetAssemblies()
            .Where(assembly => !assembly.IsDynamic && !string.IsNullOrWhiteSpace(assembly.Location))
            .Append(attributeAssembly)
            .Select(assembly => MetadataReference.CreateFromFile(assembly.Location))
            .Cast<MetadataReference>()
            .ToImmutableArray();

        var syntaxTree = CSharpSyntaxTree.ParseText(sourceCode);
        var compilation = CSharpCompilation.Create(
            assemblyName: "Macaron.PropertyAccessor.Tests",
            syntaxTrees: [syntaxTree],
            references: references,
            options: new CSharpCompilationOptions(
                outputKind: OutputKind.DynamicallyLinkedLibrary,
                nullableContextOptions: NullableContextOptions.Enable
            )
        );

        var generator = new PropertyAccessorGenerator();
        GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);

        driver = driver.RunGeneratorsAndUpdateCompilation(
            compilation,
            out var outputCompilation,
            out var generatorDiagnostics
        );

        var result = driver.GetRunResult().Results.Single();
        var generatedSources = result.GeneratedSources;
        var generatedCode = generatedSources.Length > 0 ? generatedSources[0].SourceText.ToString() : "";

        var allDiagnostics = outputCompilation.GetDiagnostics()
            .Concat(generatorDiagnostics)
            .ToImmutableArray();

        return (allDiagnostics, generatedCode);
    }

    [Test]
    public void Should_NotGenerateProperty_When_ClassIsNotMarkedWithAutoProperty()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            public partial class Foo
            {
                [Get]
                private int _answer = 42;
            }
            """,
            expected: ""
        );
    }

    [Test]
    public void Should_GenerateGet_When_FieldIsMarkedWithGetAttribute()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            public interface IBar<T> { }

            [AutoProperty]
            public partial class Foo
            {
                private int _answer0 = 42;

                [Get]
                private int _answer1 = 42;

                [Get]
                protected int m_answer2 = 42;

                [Get]
                public int answer3 = 42;

                [Get]
                public int? answer4 = null;

                [Get]
                public object? answer5 = null;

                [Get]
                public IBar<object?> answer6 = null;
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.PropertyAccessor.Tests
            {
                partial class Foo
                {
                    public int Answer1
                    {
                        get => _answer1;
                    }

                    public int Answer2
                    {
                        get => m_answer2;
                    }

                    public int Answer3
                    {
                        get => answer3;
                    }

                    public int? Answer4
                    {
                        get => answer4;
                    }

                    public object? Answer5
                    {
                        get => answer5;
                    }

                    public global::Macaron.PropertyAccessor.Tests.IBar<object?> Answer6
                    {
                        get => answer6;
                    }
                }
            }

            """
        );
    }

    [Test]
    public void Should_GenerateGetSet_When_FieldIsMarkedWithGetSetAttribute()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            [AutoProperty]
            public partial class Foo
            {
                private int _answer0 = 42;

                [GetSet]
                private int _answer1 = 42;

                [GetSet]
                protected int m_answer2 = 42;

                [GetSet]
                public int answer3 = 42;

                [GetSet]
                public int? answer4 = null;

                [GetSet]
                public object? answer5 = null;
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.PropertyAccessor.Tests
            {
                partial class Foo
                {
                    public int Answer1
                    {
                        get => _answer1;
                        set => _answer1 = value;
                    }

                    public int Answer2
                    {
                        get => m_answer2;
                        set => m_answer2 = value;
                    }

                    public int Answer3
                    {
                        get => answer3;
                        set => answer3 = value;
                    }

                    public int? Answer4
                    {
                        get => answer4;
                        set => answer4 = value;
                    }

                    public object? Answer5
                    {
                        get => answer5;
                        set => answer5 = value;
                    }
                }
            }

            """
        );
    }

    [Test]
    public void Should_GenerateInitGetSet_When_FieldIsMarkedWithGetSetAttributeWithReadonlyModifier()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            [AutoProperty]
            public partial class Foo
            {
                [GetSet]
                public readonly int _answer = 42;
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.PropertyAccessor.Tests
            {
                partial class Foo
                {
                    public int Answer
                    {
                        get => _answer;
                        init => _answer = value;
                    }
                }
            }

            """
        );
    }

    [Test]
    public void Should_GenerateGetSet_When_FieldHasGetSetAttributes()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            using System.Collections.Generic;

            namespace Macaron.PropertyAccessor.Tests;

            public sealed record Bar;

            public class Bar<TValue>
            {
            }

            [AutoProperty]
            public partial struct Foo<T>
            {
                [GetSet]
                private IReadOnlyList<Bar> _answers1;

                [GetSet]
                private Bar<T>[] _answers2;
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.PropertyAccessor.Tests
            {
                partial struct Foo<T>
                {
                    public global::System.Collections.Generic.IReadOnlyList<global::Macaron.PropertyAccessor.Tests.Bar> Answers1
                    {
                        get => _answers1;
                        set => _answers1 = value;
                    }

                    public global::Macaron.PropertyAccessor.Tests.Bar<T>[] Answers2
                    {
                        get => _answers2;
                        set => _answers2 = value;
                    }
                }
            }

            """
        );
    }

    [Test]
    public void Should_GenerateProperties_Using_CustomAccessModifierPrefixAndNamingRule()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            [AutoProperty(accessModifier: PropertyAccessModifier.Protected, prefix: "m", namingRule: PropertyNamingRule.CamelCase)]
            public partial class Foo
            {
                [Get]
                public int mAnswer = 42;
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.PropertyAccessor.Tests
            {
                partial class Foo
                {
                    protected int answer
                    {
                        get => mAnswer;
                    }
                }
            }

            """
        );
    }

    [Test]
    public void Should_OverrideClassLevelSettings_With_GetAndGetSetSettings()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            [AutoProperty(accessModifier: PropertyAccessModifier.Protected, prefix: "m", namingRule: PropertyNamingRule.CamelCase)]
            public partial class Foo
            {
                [Get(name: "bar")]
                public string _bar = "bar";

                [GetSet(accessModifier: PropertyAccessModifier.Private, name: "Answer")]
                public int m_answer = 42;

                [Get]
                public int mAnswer = 42;
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.PropertyAccessor.Tests
            {
                partial class Foo
                {
                    protected string bar
                    {
                        get => _bar;
                    }

                    private int Answer
                    {
                        get => m_answer;
                        set => m_answer = value;
                    }

                    protected int answer
                    {
                        get => mAnswer;
                    }
                }
            }

            """
        );
    }

    [Test]
    public void Should_GenerateGet_When_FieldTypeIsIReadOnlyProperty()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            [AutoProperty]
            public partial class Foo
            {
                private readonly IReadOnlyProperty<int> _answer1 = null!;
                private readonly IReadOnlyProperty<Foo, int> _answer2 = null!;
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.PropertyAccessor.Tests
            {
                partial class Foo
                {
                    public int Answer1
                    {
                        get => _answer1.Get(this);
                    }

                    public int Answer2
                    {
                        get => _answer2.Get(this);
                    }
                }
            }

            """
        );
    }

    [Test]
    public void Should_GenerateGetSet_When_FieldTypeIsIReadWriteProperty()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            [AutoProperty]
            public partial class Foo
            {
                private readonly IReadWriteProperty<int> _answer1 = null!;
                private readonly IReadWriteProperty<Foo, int> _answer2 = null!;
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.PropertyAccessor.Tests
            {
                partial class Foo
                {
                    public int Answer1
                    {
                        get => _answer1.Get(this);
                        set => _answer1.Set(this, value);
                    }

                    public int Answer2
                    {
                        get => _answer2.Get(this);
                        set => _answer2.Set(this, value);
                    }
                }
            }

            """
        );
    }

    [Test]
    public void Should_NotTreatSameNamedDifferentArityInterfaceAsDelegatedProperty()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor;

            public interface IReadOnlyProperty<T1, T2, T3>
            {
            }

            namespace Macaron.PropertyAccessor.Tests;

            [AutoProperty]
            public partial class Foo
            {
                private readonly Macaron.PropertyAccessor.IReadOnlyProperty<int, string, bool> _answer = null!;
            }
            """,
            expected: "",
            out var diagnostics
        );

        Assert.That(diagnostics, Has.None.Matches<Diagnostic>(diagnostic => diagnostic.Id.StartsWith("MPROP")));
    }

    [Test]
    public void Should_ReportDiagnosticAndNotGenerateProperty_When_IReadOnlyPropertyFieldIsNotReadonly()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            [AutoProperty]
            public partial class Foo
            {
                private IReadOnlyProperty<int> _wrongAnswer = null!;
                private readonly IReadOnlyProperty<int> _answer = null!;
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.PropertyAccessor.Tests
            {
                partial class Foo
                {
                    public int Answer
                    {
                        get => _answer.Get(this);
                    }
                }
            }

            """,
            out var diagnostics
        );

        Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic =>
            diagnostic.Id == "MPROP0001" &&
            diagnostic.GetMessage().Contains("_wrongAnswer")
        ));
    }

    [Test]
    public void Should_ReportDiagnosticAndNotGenerateProperty_When_IReadWritePropertyFieldIsNotReadonly()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            [AutoProperty]
            public partial class Foo
            {
                private IReadWriteProperty<int> _wrongAnswer = null!;

                private readonly IReadWriteProperty<int> _answer = null!;
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.PropertyAccessor.Tests
            {
                partial class Foo
                {
                    public int Answer
                    {
                        get => _answer.Get(this);
                        set => _answer.Set(this, value);
                    }
                }
            }

            """,
            out var diagnostics
        );

        Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic =>
            diagnostic.Id == "MPROP0001" &&
            diagnostic.GetMessage().Contains("_wrongAnswer")
        ));
    }

    [Test]
    public void Should_ReportDiagnostic_When_DelegatedPropertyFieldsAreNotReadonly()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            [AutoProperty]
            public partial class Foo
            {
                private IReadOnlyProperty<int> _readOnly1 = null!;
                private IReadOnlyProperty<Foo, int> _readOnly2 = null!;
                private IReadWriteProperty<int> _readWrite1 = null!;
                private IReadWriteProperty<Foo, int> _readWrite2 = null!;
            }
            """,
            expected: "",
            out var diagnostics
        );

        var readonlyDiagnostics = diagnostics
            .Where(diagnostic => diagnostic.Id == "MPROP0001")
            .ToImmutableArray();

        Assert.That(readonlyDiagnostics, Has.Length.EqualTo(4));
        Assert.That(readonlyDiagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.GetMessage().Contains("_readOnly1")));
        Assert.That(readonlyDiagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.GetMessage().Contains("_readOnly2")));
        Assert.That(readonlyDiagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.GetMessage().Contains("_readWrite1")));
        Assert.That(readonlyDiagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.GetMessage().Contains("_readWrite2")));
    }

    [Test]
    public void Should_ReportDiagnostic_When_GetOrGetSetIsAppliedToDelegatedPropertyField()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            [AutoProperty]
            public partial class Foo
            {
                [Get]
                private readonly IReadOnlyProperty<int> _answer1 = null!;

                [GetSet]
                private readonly IReadWriteProperty<int> _answer2 = null!;
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.PropertyAccessor.Tests
            {
                partial class Foo
                {
                    public int Answer1
                    {
                        get => _answer1.Get(this);
                    }

                    public int Answer2
                    {
                        get => _answer2.Get(this);
                        set => _answer2.Set(this, value);
                    }
                }
            }

            """,
            out var diagnostics
        );

        Assert.That(diagnostics.Count(diagnostic => diagnostic.Id == "MPROP0002"), Is.EqualTo(2));
    }

    [Test]
    public void Should_ReportDiagnostic_When_GeneratedPropertyNameIsEmpty()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            [AutoProperty]
            public partial class Foo
            {
                [Get] private readonly int _ = null!;
            }
            """,
            expected: "",
            out var diagnostics
        );

        Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.Id == "MPROP0004"));
    }

    [Test]
    public void Should_ReportDiagnostic_When_GeneratedPropertyNameConflictsWithFieldName()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            [AutoProperty]
            public partial class Foo
            {
                [Get] private readonly int Answer = null!;
            }
            """,
            expected: "",
            out var diagnostics
        );

        Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.Id == "MPROP0005"));
    }

    [Test]
    public void Should_ReportError_When_ClassLevelPrefixRegexIsInvalid()
    {
         AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            [AutoProperty(prefix: "[invalid")]
            public partial class Foo
            {
                [Get]
                private int _answer = 42;
            }
            """,
            expected: "",
            out var diagnostics
        );

        Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic =>
            diagnostic.Id == "MPROP0006" &&
            diagnostic.GetMessage().Contains("[invalid")
        ));
    }

    [Test]
    public void Should_ReportDiagnostic_When_FieldLevelAutoPropertyIsUsed()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            [AutoProperty]
            public partial class Foo
            {
                [AutoProperty(prefix: "_"), Get]
                private int _answer = 42;
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.PropertyAccessor.Tests
            {
                partial class Foo
                {
                    public int Answer
                    {
                        get => _answer;
                    }
                }
            }

            """,
            out var diagnostics
        );

        Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.Id == "CS0592"));
    }

    [Test]
    public void Should_UseDefaultPrefix_When_ClassLevelPrefixIsEmpty()
    {
        AssertGeneratedCode(sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            [AutoProperty(prefix: "")]
            public partial class Foo
            {
                [Get]
                private int _answer = 42;
            }
            """,
            expected:

            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.PropertyAccessor.Tests
            {
                partial class Foo
                {
                    public int Answer
                    {
                        get => _answer;
                    }
                }
            }

            """,
            out var diagnostics
        );

        Assert.That(diagnostics, Has.None.Matches<Diagnostic>(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
    }

    [Test]
    public void Should_GeneratePropertiesCorrectly_When_UsingComplexPrefixRegexPatterns()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            [AutoProperty(prefix: @"^(m_|_|s_)")]
            public partial class Foo
            {
                [Get]
                private int m_answer1 = 42;

                [Get]
                private int _answer2 = 42;

                [Get]
                private static int s_answer3 = 42;

                [Get]
                private int normalField = 42;
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.PropertyAccessor.Tests
            {
                partial class Foo
                {
                    public int Answer1
                    {
                        get => m_answer1;
                    }

                    public int Answer2
                    {
                        get => _answer2;
                    }

                    public int NormalField
                    {
                        get => normalField;
                    }
                }
            }

            """,
            out var diagnostics
        );

        Assert.That(diagnostics, Has.Some.Matches<Diagnostic>(diagnostic => diagnostic.Id == "MPROP0007"));
    }

    [Test]
    public void Should_ReportDiagnosticAndNotGenerateProperty_When_StaticFieldWouldGenerateProperty()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            [AutoProperty]
            public partial class Foo
            {
                [Get]
                private static int s_getter = 1;

                [GetSet]
                private static int s_setter = 2;

                private static readonly IReadOnlyProperty<int> s_delegated = null!;

                [Get]
                private int _answer = 42;
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.PropertyAccessor.Tests
            {
                partial class Foo
                {
                    public int Answer
                    {
                        get => _answer;
                    }
                }
            }

            """,
            out var diagnostics
        );

        Assert.That(diagnostics.Count(diagnostic => diagnostic.Id == "MPROP0007"), Is.EqualTo(3));
    }

    [Test]
    public void Should_NotApplyAutoProperty_To_NestedTypes_ByDefault()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            [AutoProperty]
            public partial class Outer
            {
                [Get]
                private int _outerField = 1;

                public partial class Inner
                {
                    [Get]
                    private int _innerField = 2;
                }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.PropertyAccessor.Tests
            {
                partial class Outer
                {
                    public int OuterField
                    {
                        get => _outerField;
                    }
                }
            }

            """
        );
    }

    [Test]
    public void Should_GenerateSingleSource_When_AutoPropertyTypeHasMultiplePartialDeclarations()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            [AutoProperty]
            public partial class Foo
            {
                [Get]
                private int _answer = 42;
            }

            public partial class Foo
            {
                [Get]
                private string _message = "hello";
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.PropertyAccessor.Tests
            {
                partial class Foo
                {
                    public int Answer
                    {
                        get => _answer;
                    }

                    public string Message
                    {
                        get => _message;
                    }
                }
            }

            """,
            out var diagnostics
        );

        Assert.That(diagnostics, Has.None.Matches<Diagnostic>(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
    }

    [Test]
    public void Should_ApplyAutoProperty_When_NestedTypeIsExplicitlyMarked()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            public partial class Outer
            {
                private int _outerField = 1;

                [AutoProperty]
                public partial class Inner
                {
                    [Get]
                    private int _innerField = 2;
                }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.PropertyAccessor.Tests
            {
                partial class Outer
                {
                    partial class Inner
                    {
                        public int InnerField
                        {
                            get => _innerField;
                        }
                    }
                }
            }

            """
        );
    }

    [Test]
    public void Should_GenerateCompilableProperties_When_TargetIsInsideNestedGenericParentTypes()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            using System.Collections.Generic;

            namespace Macaron.PropertyAccessor.Tests;

            public partial class Outer<TOuter>
            {
                public partial record Container<TContainer>
                {
                    [AutoProperty]
                    public partial struct Inner<TInner>
                    {
                        [Get]
                        private Dictionary<TOuter, (TContainer Container, TInner Inner)> _map;
                    }
                }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.PropertyAccessor.Tests
            {
                partial class Outer<TOuter>
                {
                    partial record Container<TContainer>
                    {
                        partial struct Inner<TInner>
                        {
                            public global::System.Collections.Generic.Dictionary<TOuter, (TContainer Container, TInner Inner)> Map
                            {
                                get => _map;
                            }
                        }
                    }
                }
            }

            """,
            out var diagnostics
        );

        Assert.That(diagnostics, Has.None.Matches<Diagnostic>(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
    }

    [Test]
    public void Should_GenerateCompilableProperties_When_TargetsAreRecords()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            [AutoProperty]
            public partial record Person
            {
                [Get]
                private string _name = "";
            }

            [AutoProperty]
            public readonly partial record struct Point
            {
                [Get]
                private readonly int _x;
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.PropertyAccessor.Tests
            {
                partial record Person
                {
                    public string Name
                    {
                        get => _name;
                    }
                }
            }

            """,
            out var diagnostics
        );

        Assert.That(diagnostics, Has.None.Matches<Diagnostic>(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
    }

    [Test]
    public void Should_GenerateProperties_When_GenericTypeConstraintsAreApplied()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            using System;
            using System.Collections.Generic;

            namespace Macaron.PropertyAccessor.Tests;

            [AutoProperty]
            public partial class GenericClass<T, U>
                where T : class, IComparable<T>
                where U : struct
            {
                [GetSet]
                private T _item;

                [Get]
                private readonly U _value;

                [GetSet]
                private List<T> _items;
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.PropertyAccessor.Tests
            {
                partial class GenericClass<T, U>
                {
                    public T Item
                    {
                        get => _item;
                        set => _item = value;
                    }

                    public U Value
                    {
                        get => _value;
                    }

                    public global::System.Collections.Generic.List<T> Items
                    {
                        get => _items;
                        set => _items = value;
                    }
                }
            }

            """
        );
    }

    [Test]
    public void Should_GenerateProperties_When_FieldsHaveNestedGenericOrTupleTypes()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            using System;
            using System.Collections.Generic;

            namespace Macaron.PropertyAccessor.Tests;

            [AutoProperty]
            public partial class ComplexGenericClass<T>
            {
                [GetSet]
                private Dictionary<string, List<T>> _complexField;

                [Get]
                private readonly Func<T, bool> _predicate;

                [GetSet]
                private (int id, T value) _tupleField;
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.PropertyAccessor.Tests
            {
                partial class ComplexGenericClass<T>
                {
                    public global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<T>> ComplexField
                    {
                        get => _complexField;
                        set => _complexField = value;
                    }

                    public global::System.Func<T, bool> Predicate
                    {
                        get => _predicate;
                    }

                    public (int id, T value) TupleField
                    {
                        get => _tupleField;
                        set => _tupleField = value;
                    }
                }
            }

            """
        );
    }

    [Test]
    public void Should_GenerateProperties_When_FieldNamesContainSpecialCharacters()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.PropertyAccessor.Tests;

            [AutoProperty]
            public partial class SpecialCharacterClass
            {
                [Get]
                private int @class = 1;

                [Get]
                private string _ünicodeField = "";

                [Get]
                private bool _field123 = false;

                [Get]
                private double __doubleUnderscore1 = 0.0;

                [Get(name: "DoubleUnderscore2")]
                private double __doubleUnderscore2 = 0.0;
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.PropertyAccessor.Tests
            {
                partial class SpecialCharacterClass
                {
                    public int Class
                    {
                        get => @class;
                    }

                    public string ÜnicodeField
                    {
                        get => _ünicodeField;
                    }

                    public bool Field123
                    {
                        get => _field123;
                    }

                    public double _doubleUnderscore1
                    {
                        get => __doubleUnderscore1;
                    }

                    public double DoubleUnderscore2
                    {
                        get => __doubleUnderscore2;
                    }
                }
            }

            """
        );
    }
}
