using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFacts;
using static Microsoft.CodeAnalysis.SymbolDisplayFormat;
using static Microsoft.CodeAnalysis.SymbolDisplayMiscellaneousOptions;

namespace Macaron.PropertyAccessor;

public static class SourceGenerationHelpers
{
    #region Constants
    private const string Indent = "    ";
    #endregion

    #region Methods
    public static ImmutableArray<string> GenerateAccessorCode(PropertyContext propertyContext)
    {
        var (
            accessModifier,
            typeSymbol,
            propertyName,
            fieldName,
            accessorKind,
            isInitAccessor,
            getterRequiresExplicitConversion
        ) = propertyContext;

        if (accessorKind == PropertyAccessorKind.None)
        {
            return ImmutableArray<string>.Empty;
        }

        var escapedFieldName = GetEscapedIdentifier(fieldName);
        var escapedPropertyName = GetEscapedIdentifier(propertyName);
        var propertyTypeName = typeSymbol.ToDisplayString(FullyQualifiedFormat.WithMiscellaneousOptions(
            IncludeNullableReferenceTypeModifier | UseSpecialTypes
        ));

        var builder = ImmutableArray.CreateBuilder<string>();

        builder.Add($"{GetAccessorModifier(accessModifier)} {propertyTypeName} {escapedPropertyName}");
        builder.Add("{");

        if (accessorKind is PropertyAccessorKind.Get or PropertyAccessorKind.GetSet)
        {
            var getterExpression = escapedFieldName;

            if (getterRequiresExplicitConversion)
            {
                getterExpression = $"({propertyTypeName}){getterExpression}";
            }

            builder.Add($"{Indent}get => {getterExpression};");
        }

        if (accessorKind == PropertyAccessorKind.GetSet)
        {
            builder.Add($"{Indent}{(isInitAccessor ? "init" : "set")} => {escapedFieldName} = value;");
        }

        builder.Add("}");

        return builder.ToImmutable();
    }

    public static void AddSource(
        SourceProductionContext context,
        INamedTypeSymbol typeSymbol,
        ImmutableArray<string> lines
    )
    {
        if (lines.IsDefaultOrEmpty)
        {
            return;
        }

        var stringBuilder = CreateStringBuilderWithFileHeader();

        // begin namespace
        var hasNamespace = !typeSymbol.ContainingNamespace.IsGlobalNamespace;
        if (hasNamespace)
        {
            stringBuilder.AppendLine($"namespace {typeSymbol.ContainingNamespace.ToDisplayString()}");
            stringBuilder.AppendLine($"{{");
        }

        // get nestedTypes
        var nestedTypes = new List<INamedTypeSymbol>();
        var parentType = typeSymbol.ContainingType;
        while (parentType != null)
        {
            nestedTypes.Add(parentType);
            parentType = parentType.ContainingType;
        }

        var depthSpacerText = hasNamespace ? $"{Indent}" : "";

        // begin nestedTypes
        for (var i = nestedTypes.Count - 1; i >= 0; --i)
        {
            var nestedType = nestedTypes[i];

            stringBuilder.AppendLine($"{depthSpacerText}{GetPartialTypeDeclarationString(nestedType)}");
            stringBuilder.AppendLine($"{depthSpacerText}{{");

            depthSpacerText += $"{Indent}";
        }

        // begin containingType
        stringBuilder.AppendLine($"{depthSpacerText}{GetPartialTypeDeclarationString(typeSymbol)}");
        stringBuilder.AppendLine($"{depthSpacerText}{{");

        // generate factory methods
        depthSpacerText += $"{Indent}";

        foreach (var line in lines)
        {
            stringBuilder.AppendLine($"{(line.Length > 0 ? depthSpacerText : "")}{line}");
        }

        depthSpacerText = depthSpacerText[..^4];

        // end containedType
        stringBuilder.AppendLine($"{depthSpacerText}}}");

        // end nestedTypes
        for (var i = 0; i < nestedTypes.Count; ++i)
        {
            depthSpacerText = depthSpacerText[..^4];

            stringBuilder.AppendLine($"{depthSpacerText}}}");
        }

        // end namespace
        if (hasNamespace)
        {
            stringBuilder.AppendLine($"}}");
        }

        context.AddSource(
            hintName: GetHintName(typeSymbol),
            sourceText: SourceText.From(stringBuilder.ToString(), Encoding.UTF8)
        );
    }

    private static StringBuilder CreateStringBuilderWithFileHeader()
    {
        var stringBuilder = new StringBuilder();
        stringBuilder.AppendLine("// <auto-generated />");
        stringBuilder.AppendLine("#nullable enable");
        stringBuilder.AppendLine();

        return stringBuilder;
    }

    private static string GetAccessorModifier(PropertyAccessModifier accessModifier)
    {
        return accessModifier switch
        {
            PropertyAccessModifier.Public => "public",
            PropertyAccessModifier.Protected => "protected",
            PropertyAccessModifier.Internal => "internal",
            PropertyAccessModifier.Private => "private",
            PropertyAccessModifier.ProtectedInternal => "protected internal",
            PropertyAccessModifier.PrivateProtected => "private protected",
            PropertyAccessModifier.File => "file",
            _ => throw new InvalidOperationException($"Invalid access modifier: {accessModifier}"),
        };
    }

    private static string GetPartialTypeDeclarationString(INamedTypeSymbol typeSymbol)
    {
        var typeModifier = typeSymbol.IsReadOnly ? "readonly " : "";
        var typeKind = GetTypeKindString(typeSymbol);
        var typeName = GetTypeNameString(typeSymbol);

        return $"{typeModifier}partial {typeKind} {typeName}";
    }

    private static string GetTypeNameString(INamedTypeSymbol typeSymbol)
    {
        var typeName = GetEscapedIdentifier(typeSymbol.Name);
        if (typeSymbol.TypeParameters.Length == 0)
        {
            return typeName;
        }

        var typeParameters = typeSymbol
            .TypeParameters
            .Select(typeParameter => GetEscapedIdentifier(typeParameter.Name));

        return $"{typeName}<{string.Join(", ", typeParameters)}>";
    }

    private static string GetHintName(INamedTypeSymbol typeSymbol)
    {
        var qualifiedName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        const uint fnvPrime = 16777619;
        const uint offsetBasis = 2166136261;

        var bytes = Encoding.UTF8.GetBytes($"{qualifiedName}");
        var hash = offsetBasis;

        foreach (var b in bytes)
        {
            hash ^= b;
            hash *= fnvPrime;
        }

        return $"{typeSymbol.Name}_{typeSymbol.Arity}.{hash:x8}.g.cs";
    }

    private static string GetTypeKindString(INamedTypeSymbol typeSymbol)
    {
        if (typeSymbol.IsRecord)
        {
            return typeSymbol.TypeKind is TypeKind.Struct ? "record struct" : "record";
        }

        return typeSymbol.TypeKind switch
        {
            TypeKind.Class => "class",
            TypeKind.Struct => "struct",
            TypeKind.Interface => "interface",
            _ => throw new InvalidOperationException($"Invalid type kind: {typeSymbol.TypeKind}"),
        };
    }

    private static string GetEscapedIdentifier(string identifier)
    {
        return GetKeywordKind(identifier) != SyntaxKind.None
            || GetContextualKeywordKind(identifier) != SyntaxKind.None
            ? "@" + identifier
            : identifier;
    }
    #endregion
}
