using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFacts;

namespace Macaron.PropertyAccessor;

internal static class SourceGenerationHelpers
{
    #region Constants
    private const string Indent = "    ";
    #endregion

    #region Methods
    public static string GetSource(GenerationModel generationModel)
    {
        var stringBuilder = new StringBuilder();

        stringBuilder.AppendLine("// <auto-generated />");
        stringBuilder.AppendLine("#nullable enable");
        stringBuilder.AppendLine();

        var typeModel = generationModel.Type;

        // namespace begin
        var hasNamespace = typeModel.NamespaceName.Length > 0;

        if (hasNamespace)
        {
            stringBuilder.AppendLine($"namespace {typeModel.NamespaceName}");
            stringBuilder.AppendLine("{");
        }

        var depthSpacerText = hasNamespace ? Indent : "";

        // type declaration begin
        foreach (var declaration in typeModel.Declarations)
        {
            stringBuilder.AppendLine($"{depthSpacerText}{declaration}");
            stringBuilder.AppendLine($"{depthSpacerText}{{");

            depthSpacerText += Indent;
        }

        // properties
        var hasProperty = false;

        foreach (var propertyModel in generationModel.Properties)
        {
            var lines = GenerateAccessorCode(propertyModel);

            if (lines.IsEmpty)
            {
                continue;
            }

            if (hasProperty)
            {
                stringBuilder.AppendLine();
            }

            foreach (var line in lines)
            {
                stringBuilder.AppendLine($"{depthSpacerText}{line}");
            }

            hasProperty = true;
        }

        // type declaration end
        for (var i = 0; i < typeModel.Declarations.Length; ++i)
        {
            depthSpacerText = depthSpacerText[..^Indent.Length];
            stringBuilder.AppendLine($"{depthSpacerText}}}");
        }

        // namespace end
        if (hasNamespace)
        {
            stringBuilder.AppendLine("}");
        }

        return stringBuilder.ToString();
    }

    private static ImmutableArray<string> GenerateAccessorCode(PropertyModel propertyModel)
    {
        var (
            accessModifier,
            propertyTypeName,
            propertyName,
            fieldName,
            accessorKind,
            isInitAccessor,
            getterRequiresExplicitConversion
        ) = propertyModel;

        if (accessorKind == PropertyAccessorKind.None)
        {
            return ImmutableArray<string>.Empty;
        }

        var escapedFieldName = GetEscapedIdentifier(fieldName);
        var escapedPropertyName = GetEscapedIdentifier(propertyName);
        var builder = ImmutableArray.CreateBuilder<string>();

        builder.Add($"{GetAccessorModifier(accessModifier)} {propertyTypeName} {escapedPropertyName}");
        builder.Add("{");

        if (accessorKind is PropertyAccessorKind.Get or PropertyAccessorKind.GetSet)
        {
            var getterExpression = escapedFieldName;

            if (getterRequiresExplicitConversion)
            {
                getterExpression = $"({propertyTypeName}){getterExpression}";
            }

            builder.Add($"{Indent}get => {getterExpression};");
        }

        if (accessorKind == PropertyAccessorKind.GetSet)
        {
            builder.Add($"{Indent}{(isInitAccessor ? "init" : "set")} => {escapedFieldName} = value;");
        }

        builder.Add("}");

        return builder.ToImmutable();
    }

    private static string GetAccessorModifier(PropertyAccessModifier accessModifier)
    {
        return accessModifier switch
        {
            PropertyAccessModifier.Public => "public",
            PropertyAccessModifier.Protected => "protected",
            PropertyAccessModifier.Internal => "internal",
            PropertyAccessModifier.Private => "private",
            PropertyAccessModifier.ProtectedInternal => "protected internal",
            PropertyAccessModifier.PrivateProtected => "private protected",
            PropertyAccessModifier.File => "file",
            _ => throw new InvalidOperationException($"Invalid access modifier: {accessModifier}"),
        };
    }

    private static string GetEscapedIdentifier(string identifier)
    {
        return GetKeywordKind(identifier) != SyntaxKind.None
            || GetContextualKeywordKind(identifier) != SyntaxKind.None
            ? "@" + identifier
            : identifier;
    }
    #endregion
}
